### ISSUE TITLE
where clause should support missing data.

### ISSUE THREAD

**Issue by v0dro** [SciRuby/daru#246]
When `#where` is called on a Vector/DataFrame, it should not fail if the data contains missing data.

**Comment by lokeshh** [comment]
Could you share a case where it fails?

**Comment by v0dro** [comment]
Here you go:
```
2.2.1 :011 >   v= Daru::Vector.new([1,2,3,Float::NAN, nil])
 => #<Daru::Vector(5)>
   0   1
   1   2
   2   3
   3 NaN
   4 nil 
2.2.1 :012 > v.where(v.lt(4))
NoMethodError: undefined method `<' for nil:NilClass
	from /home/sameer/.rvm/gems/ruby-2.2.1/gems/daru-0.1.4.1/lib/daru/core/query.rb:42:in `block in apply_scalar_operator'
	from /home/sameer/.rvm/gems/ruby-2.2.1/gems/daru-0.1.4.1/lib/daru/accessors/array_wrapper.rb:11:in `each'
	from /home/sameer/.rvm/gems/ruby-2.2.1/gems/daru-0.1.4.1/lib/daru/accessors/array_wrapper.rb:11:in `each'
	from /home/sameer/.rvm/gems/ruby-2.2.1/gems/daru-0.1.4.1/lib/daru/core/query.rb:42:in `map'
	from /home/sameer/.rvm/gems/ruby-2.2.1/gems/daru-0.1.4.1/lib/daru/core/query.rb:42:in `apply_scalar_operator'
	from /home/sameer/.rvm/gems/ruby-2.2.1/gems/daru-0.1.4.1/lib/daru/vector.rb:353:in `block (2 levels) in <class:Vector>'
	from (irb):12
	from /home/sameer/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

**Comment by athityakumar** [comment]
If this issue hasn't been fixed yet, I can work on this - if assigned.

Ping @lokeshh @v0dro

**Comment by v0dro** [comment]
The expectation is that missing data (as in `nil` or `Float::NaN`) should be supported by the `where` clause irrespective of the kind of data in the vector/dataframe.

You can check out the README for more example of `where`.
