### ISSUE TITLE
Error when using Group by with single row Data Frame

### ISSUE THREAD

**Issue by IdeoConcepts** [SciRuby/daru#438]
Hi,

With Daru v0.2.0, it seems that if the DataFrame has only one row, the group_by method will fail with "ArgumentError: Can't create DataFrame from xx" error.

Example:
````
> df = Daru::DataFrame.new({a: [1], b: [2]})
> df.group_by([:a])
ArgumentError: Can't create DataFrame from [2]
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/daru-0.2.0/lib/daru/dataframe.rb:176:in `rows'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/daru-0.2.0/lib/daru/core/group_by.rb:351:in `resultant_context'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/daru-0.2.0/lib/daru/core/group_by.rb:302:in `init_groups_df'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/daru-0.2.0/lib/daru/core/group_by.rb:37:in `initialize'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/daru-0.2.0/lib/daru/dataframe.rb:1461:in `new'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/daru-0.2.0/lib/daru/dataframe.rb:1461:in `group_by'`
   
````    
Whereas a multi rows DataFrame will be fine.
````
> df = Daru::DataFrame.new({a: [1,3], b: [2,4]})
> df.group_by([:a])
 => #<Daru::DataFrame(2x1)>
           b
   1   0   2
   3   1   4
````
Many thanks

**Comment by baarkerlounger** [comment]
A group_by on a single row dataframe should just return that same dataframe right?

**Comment by baarkerlounger** [comment]
Can this be closed given the above has been merged?
