### ISSUE TITLE
DataFrame#plot and Vector#plot not working

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/daru#482]
```ruby
require 'daru'
Daru.plotting_library = :gruff
dv = Daru::Vector.new [1, 2, 3]
dv.plot do |p|
  p.title = 'lol'
end
```
result in following error:

```
SystemStackError: stack level too deep
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru.rb:54:in `block in create_has_library'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:209:in `plotting_library='
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:1498:in `init_plotting_library'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:222:in `plot'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:224:in `plot'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:224:in `plot'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:224:in `plot'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:224:in `plot'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:224:in `plot'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:224:in `plot'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:224:in `plot'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:224:in `plot'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:224:in `plot'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:224:in `plot'
/var/lib/gems/2.5.0/gems/daru-0.2.1/lib/daru/vector.rb:224:in `plot'
...
```

If looks to me the support for plotting in Daru has been removed or long been broken because Daru latest release gives the error that `DataFrame#plot` is not found. If the support for plotting has been removed we need to remove the appropriate notebooks from README and `sciruby-notebooks`.

**Comment by lokeshh** [comment]
@Shekharrajak Ok, but these lines are certainly not working in latest daru release.

**Comment by Shekharrajak** [comment]
Yes! I already tried the latest cloned version : 

```
 ➜  daru git:(master*) bundle console 
irb(main):001:0> require 'daru'
=> false
irb(main):002:0> Daru.plotting_library = :gruff
=> :gruff
irb(main):003:0> dv = Daru::Vector.new [1, 2, 3]
=> #<Daru::Vector(3)>
   0   1
   1   2
   2   3
irb(main):004:0> dv.plot do |p|
irb(main):005:1*   p.title = 'lol'
irb(main):006:1> end
=> #<Gruff::Bar:0x000055ae4fac16a8 @columns=500.0 .................

```

I'll check 0.2.1

**Comment by Shekharrajak** [comment]
Thanks for update.

**Comment by lokeshh** [comment]
I think a new Daru release is needed as with the last release the `sciruby-notebooks` won't be working. Also could you verify if `gnuplot` working for you?

Following lines give me `Illegal seek` error. What about you?
```ruby
require 'gnuplotrb'
require 'daru'
include GnuplotRB

dv = Daru::Vector.new [:a, :a, :a, :b, :b], type: :category
Plot.new [dv.frequencies, with: 'histogram'], xrange: -1..2, yrange: 0..10
```

**Comment by Shekharrajak** [comment]
@lokeshh , I installed `gnuplotrb` gem  and run `sudo apt-get install gnuplot-x11`. It worked for me.

**Comment by lokeshh** [comment]
Ok thanks.

**Comment by homonecloco** [comment]
Hi, 
I'm having the same error, I'm using Daru-0.2.2.  Is this something fixed in the master branch? And if so, are you planning to do a release at some point? I prefer to use a fixed release for consistency. 
Best, 
Ricardo.

**Comment by NicolasNeiman** [comment]
Hi @lokeshh  and @v0dro,
I'm using daru (0.3) and I'm getting the same error 

`SystemStackError: stack level too deep`

Do you have the same issue on your end ?

**Comment by lokeshh** [comment]
@NicolasNeiman You need to install `gruff` gem first. You can do that by running `gem install gruff`.

**Comment by lokeshh** [comment]
@homonecloco I'm using daru 0.3 and plotting with gruff is working for me. I just had to add that gem using `gem install gruff`. If you see an let me know.
